name: skoller
description: A new Flutter project.
version: 6.6.0+34

# I manually upgraded Dart SDK version to 2.14 to access Enum's name features.
# It shouldn't be done this way. Dart SDK are automatically updated when updating Flutter.
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  #charts_flutter: ^0.6.0
  charts_flutter: ^0.11.0
  #dart_notification_center: ^1.0.0
  dart_notification_center: ^1.0.0+1
  dropdown_banner: ^1.4.0
  #http: ^0.12.0+1
  http: ^0.13.3
  #image_picker: ^0.6.3+1
  image_picker: ^0.8.2
  #intl: ^0.15.8
  intl: ^0.17.0
  #auto_size_text: ^1.1.2
  auto_size_text: ^2.1.0
  #time_machine: ^0.9.9
  time_machine: ^0.9.16
  #flutter_slidable: ^0.5.0
  flutter_slidable: ^0.6.0
  #firebase_analytics: ^4.0.2
  firebase_analytics: ^8.2.0
  #firebase_core: ^0.4.0+8
  firebase_core: ^1.4.0
  #firebase_messaging: ^5.1.2
  firebase_messaging: ^10.0.4
  #flutter_apns: ^1.0.5
  flutter_apns: ^1.5.1
  #flutter_keychain: ^1.0.0
  flutter_keychain: ^2.0.1
  in_app_purchase: ^3.0.7
  package_info: ^2.0.2
  path_provider: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  app_review: ^2.1.1+1
  webview_flutter: ^2.0.10
  camera: ^0.10.0
  image: ^3.0.2
  flutter_multi_formatter: ^2.3.5
  fluttertoast: ^7.1.1
  rxdart: ^0.27.2
#  stripe_payment: ^1.1.4
#  flutter_stripe: ^4.0.0
  screen_loader: ^2.0.1
  pay: ^1.0.6


  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - image_assets/tab_bar_assets/
    - image_assets/sign_up_assets/
    - image_assets/todo_assets/
    - image_assets/classes_assets/
    - image_assets/navigation_arrow_assets/
    - image_assets/right_button_assets/
    - image_assets/assignment_info_assets/
    - image_assets/people_assets/
    - image_assets/status_assets/
    - image_assets/activity_assets/
    - image_assets/sammi_jobs_personality_assets/
    - image_assets/class_info_assets/
    - image_assets/sammi_personality_assets/
    - image_assets/menu_assets/
    - image_assets/jobs_assets/
    - image_assets/tutorial_assets/
    - image_assets/share_assets/
    - image_assets/todolist_gif_assets/
    - assets/
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin